### ISSUE TITLE
Docs -> Public

### ISSUE THREAD

**Issue by ncammarata** [psturmfels/VisualizingExpectedGradients#4]
Hi,

I'm on the Distill team and I'm looking to put your article on Distill's staging server so it's ready to go! Unfortunately, our setup currently uses `public` for rendering the static assets instead of `docs`, which gh-pages uses. We're looking at allowing configurable folders in the future, but since we don't have that yet would you mind changing the folder?

Thanks!
Nick

**Comment by psturmfels** [comment]
Ah of course! Is this as simple as changing the name of the docs folder to “public”?

**Comment by psturmfels** [comment]
I've just changed the folder name. Let me know if this was _not_ what you intended.

**Comment by ncammarata** [comment]
Looks good -- thanks Pascal!
